# Generated by Django 5.1.3 on 2024-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
