# Generated by Django 5.1.3 on 2024-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('product_price', models.IntegerField(default=0)),
                ('product_GST', models.FloatField(default=0)),
            ],
        ),
    ]
