# Generated by Django 5.1.3 on 2024-11-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
